// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: answer.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAnswer = `-- name: CreateAnswer :exec
insert into "answers" (answer_id, author_id, question_id, content, created_at, updated_at) values ($1, $2, $3, $4, $5, $6)
`

type CreateAnswerParams struct {
	AnswerID   uuid.UUID
	AuthorID   uuid.UUID
	QuestionID uuid.UUID
	Content    string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) error {
	_, err := q.db.ExecContext(ctx, createAnswer,
		arg.AnswerID,
		arg.AuthorID,
		arg.QuestionID,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
