// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Question struct {
	QuestionID   uuid.UUID
	AuthorID     uuid.UUID
	BestAnswerID uuid.NullUUID
	Slug         string
	Title        string
	Content      string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Student struct {
	StudentID uuid.UUID
	Name      string
}
