package controllers

type AnswerControllers struct {
	AnswerQuestionController *DefaultAnswerQuestionControllerInterface
}

type QuestionControllers struct {
	CreateQuestionController     *DefaultCreateQuestionControllerInterface
	GetQuestionBySlugController  *DefaultGetQuestionBySlugControllerInterface
	GetRecentQuestionsController *DefaultGetRecentQuestionsControllerInterface
	DeleteQuestionByIDController *DefaultDeleteQuestionByIDControllerInterface
}

type UserControllers struct {
	SignUpController *DefaultSignUpControllerInterface
	SignInController *DefaultSignInControllerInterface
}
